sudo: required
language: node_js
node_js:  
  - node
services:
  - docker
env: DOCKER_COMPOSE_VERSION=1.18.0
before_install:
  - sudo /etc/init.d/mysql stop
  - npm install codecov -g
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker info
script:
  - docker-compose -f docker-compose-travis.yml -p hierax build
  - docker-compose -f docker-compose-travis.yml -p hierax up -d
  - docker ps -a
  - docker-compose exec hierax-api npm test
after_success:
  - sudo pip install codecov
  - codecov
deploy:
  provider: heroku
  api_key:
    secure: vVPNJ9LcHiCKSjBcXAo+ClpULoWS35SfFMbPaISIlmgyOa8xgdNSuaXmyAN5czwEYBL9Wbrp/7pgxYhSBaiXNd+LX5Fxq2nnmzlhwBe5xZhh3Tth0mx+GKKNsLpGigbHPcqezdOIKeaxTRAIkpc5vKuUUzhlT3AXQi11rWUKZDNJsAzO5wjVTO1kPmHpAeFkAyHLUnUz+d0xZdxULVubTp3atDgViIn1njz+g2nrkJeTz4Y1fTsjRJvyZ3tuAI1TGAhLVMVOab794RTkrcYsL3Oj4gHNB98tVEashaxndXoNIRnrSFCOCnbJG8HlfcQ9nHm+/FQxk+25osTjJdnhBBh6rITbZo9Tyziy3o4juIrVe/oLGdf/tWInbAiYwY1bGylHsC6bRmQ+Jtq8ulMc15FYhn3FCErrEutegUrOZQZJn/KJI4U6mS8nONTKMnleu9LacDw7wNFEvTUATQ1J2uB4zhpbn4WXiKfCljn3FFl+JtISb8Z/uaMvbKgN9sDylMd39KPIaUxsZrJlb83iv4G+IDu/fP7krWFdS3fwtSoPg4WjlNkw20pKrd/f2h7zbDCTGWnz0GXLVBl2Y24HCfL61o2FZdS1xPDBNpdhVLSepBNlIWQ2o1RL+/m8hhWZgaLn7txGK7soCrSwDc6iVcAn7VZLhSEMNQ5hh+qY1TE=
